<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="0" ignored="0" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="133" started-at="2019-09-17T12:05:42 IST" finished-at="2019-09-17T12:05:42 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="133" started-at="2019-09-17T12:05:42 IST" finished-at="2019-09-17T12:05:42 IST">
      <class name="testng.Login">
        <test-method status="PASS" signature="beforetestmethod()[pri:0, instance:testng.Login@2286778]" name="beforetestmethod" is-config="true" duration-ms="12" started-at="2019-09-17T12:05:42 IST" finished-at="2019-09-17T12:05:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforetestmethod -->
        <test-method status="PASS" signature="beforemethod()[pri:0, instance:testng.Login@2286778]" name="beforemethod" is-config="true" duration-ms="0" started-at="2019-09-17T12:05:42 IST" finished-at="2019-09-17T12:05:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforemethod -->
        <test-method status="SKIP" signature="testlogin()[pri:1, instance:testng.Login@2286778]" name="testlogin" duration-ms="6" started-at="2019-09-17T12:05:42 IST" finished-at="2019-09-17T12:05:42 IST">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[reason]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: reason
at testng.Login.testlogin(Login.java:14)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testlogin -->
        <test-method status="PASS" signature="feforemethod()[pri:0, instance:testng.Login@2286778]" name="feforemethod" is-config="true" duration-ms="1" started-at="2019-09-17T12:05:42 IST" finished-at="2019-09-17T12:05:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feforemethod -->
        <test-method status="SKIP" signature="password()[pri:2, instance:testng.Login@2286778]" name="password" duration-ms="0" started-at="2019-09-17T12:05:42 IST" depends-on-methods="testng.Login.testlogin" finished-at="2019-09-17T12:05:42 IST">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Login.password()[pri:2, instance:testng.Login@2286778] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Login.password()[pri:2, instance:testng.Login@2286778] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:99)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- password -->
        <test-method status="SKIP" signature="logout()[pri:3, instance:testng.Login@2286778]" name="logout" duration-ms="0" started-at="2019-09-17T12:05:42 IST" depends-on-methods="testng.Login.password, testng.Login.testlogin" finished-at="2019-09-17T12:05:42 IST">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Login.logout()[pri:3, instance:testng.Login@2286778] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Login.logout()[pri:3, instance:testng.Login@2286778] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:99)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method status="PASS" signature="aftertestmethod()[pri:0, instance:testng.Login@2286778]" name="aftertestmethod" is-config="true" duration-ms="0" started-at="2019-09-17T12:05:42 IST" finished-at="2019-09-17T12:05:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftertestmethod -->
      </class> <!-- testng.Login -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
